### ISSUE TITLE
App Crashes When Loading Hundreds of Edits

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/openmapkit#47]
Probably a thread problem. Probably somewhere in OSMMapBuilder.java

**Comment by hallahan** [comment]
Finding exceptions being thrown:

```
03-26 01:27:45.018  24095-25391/org.redcross.openmapkit W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
03-26 01:27:45.018  24095-25391/org.redcross.openmapkit W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
03-26 01:27:45.018  24095-25393/org.redcross.openmapkit W/System.err﹕ java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
03-26 01:27:45.018  24095-25393/org.redcross.openmapkit W/System.err﹕ at com.spatialdev.osm.model.JTSModel.mergeEditedOSMDataSet(JTSModel.java:49)
03-26 01:27:45.018  24095-25393/org.redcross.openmapkit W/System.err﹕ at org.redcross.openmapkit.OSMMapBuilder.doInBackground(OSMMapBuilder.java:125)
03-26 01:27:45.018  24095-25393/org.redcross.openmapkit W/System.err﹕ at org.redcross.openmapkit.OSMMapBuilder.doInBackground(OSMMapBuilder.java:35)
```

Something funky with threads removing old ways from existing data set.

**Comment by hallahan** [comment]
Progress bar sometimes halts and is saying "Parsing 141 of 1 OSM XML files."

**Comment by hallahan** [comment]
Still getting this sometimes:

![wrong](https://cloud.githubusercontent.com/assets/556367/6858425/a351559e-d3cb-11e4-85fd-16eba02dccde.png)
